update aiidalab server role
aiidalab/ansible-playbook-aiidalab-server pull request #5
Opened 2020-08-20 08:45 UTC by unkcpz

The ansible role in `marvel-nccr` is no longer update. 

If so, the README.md of `ansible-role-aiidalab-server` repository should also updated, right?

2020-08-20 14:58 UTC, ltalirz requested changes
Thanks @unkcpz - one change request.

2020-08-20 14:58 UTC, ltalirz commented on playbook.yml
> +    - role: ansible-role-aiidalab-server
One is the name of the git repo; the other is the name on ansible galaxy.
I'm pretty sure the old one is correct (correct me if I'm wrong)

2020-08-24 07:05 UTC, unkcpz reviewed
I forgot to submit review..

2020-08-24 07:05 UTC, unkcpz commented on playbook.yml
> +    - role: ansible-role-aiidalab-server
No, the old one point to https://galaxy.ansible.com/marvel-nccr/aiidalab_server whose latest version is `v0.2.1` updated 5 month before and its repository then redirect to this repository. 

The name of role here depend on how user rename the role, if no specific name in `requirements.yml` it will use the name of the role source.

2020-08-24 07:32 UTC, ltalirz commented
Hi Jason, I don't think this is correct - I just checked:

```
$ ansible-galaxy install -r requirements.yml
- downloading role 'aiidalab_server', owned by marvel-nccr
- downloading role from https://github.com/marvel-nccr/ansible-role-aiidalab-server/archive/master.tar.gz
- extracting marvel-nccr.aiidalab_server to /Users/leopold/Personal/Postdoc-MARVEL/repos/aiidalab/ansible-playbook-aiidalab-server/roles/marvel-nccr.aiidalab_server
```
let me know if it works differently for you (and which ansible galaxy version you have)

2020-08-24 07:46 UTC, unkcpz commented
Sure, the previous one is also working but the link https://github.com/marvel-nccr/ansible-role-aiidalab-server is redirect to https://github.com/aiidalab/ansible-role-aiidalab-server . For example, if you want install the latest role version v0.3.0, the role will not be found.

2020-08-24 07:48 UTC, unkcpz commented
Or did I get it wrong?

2020-08-24 07:55 UTC, ltalirz commented
If you follow the installation instructions in the README, you will use `ansible-galaxy install -r requirements.yml` in order to install the role. As my output above shows, this causes the `master` branch to be installed to `roles/marvel-nccr.aiidalab_server` (right?)

2020-08-24 08:11 UTC, unkcpz commented
Notice I also changed `requirements.yml`. My point is https://github.com/marvel-nccr/ansible-role-aiidalab-server is no longer maintained and we should use the aiidalab/ansible-role-aiidalab-server directly in requirements.yml

2020-08-24 08:12 UTC, unkcpz commented on requirements.yml
> -  version: v0.2.1
Here, `marvel-nccr.aiidalab_server` do not have master branch or v0.3.0.

2020-08-24 08:16 UTC, ltalirz commented
Ok, now I understand the confusion ;-)

The name of the role in ansible galaxy has stayed the same, but it now points to the new github repository because of github's redirection policy.
I.e. when the log says
```
- downloading role from https://github.com/marvel-nccr/ansible-role-aiidalab-server/archive/master.tar.gz
```
it is actually downloading from
```
https://github.com/aiidalab/ansible-role-aiidalab-server/archive/master.tar.gz
```

You can easily verify this by checking the content of the download.

2020-08-24 08:31 UTC, unkcpz commented
Ha, yes! it works for master, but not for specific version for example you can check it with v0.3.0 in requirements.yml.
Since marvel-nccr is removed, why don't we change all the url to the new one?

2020-08-24 08:49 UTC, ltalirz commented
> Since marvel-nccr is removed, why don't we change all the url to the new one?

This would involve creating a new provider namespace on ansible galaxy.
We could do it but currently the marvel-nccr namespace bundles all the ansible roles that we have, which simplifies maintenance a bit.
However, that's up to you guys - mentioning @yakutovicha as well

> it works for master, but not for specific version for example you can check it with v0.3.0 in requirements.yml.

Right, that surprised me a bit. I just imported the role manually and now it has the latest v0.3 tag.

It seems to suggest that somehow the webhook https://github.com/aiidalab/ansible-role-aiidalab-server/blob/master/.travis.yml#L36 is no longer working. 
I don't see a way to edit the link to the repository in ansible galaxy, so perhaps it's better to [create a new namespace](https://galaxy.ansible.com/docs/contributing/namespaces.html)

@unkcpz You are welcome to do it and to invite Sasha and me.

2020-08-25 11:32 UTC, unkcpz commented
Hi @ltalirz I hope I did it right https://github.com/ansible/galaxy/issues/2480

2020-08-25 11:36 UTC, unkcpz commented
I have a question: how does ansible know there is new release in that repository? Do we need make some change in the role repository?

2020-08-25 13:24 UTC, ltalirz commented
> Hi @ltalirz I hope I did it right ansible/galaxy#2480

Thanks, looks like it ;-)  I don't remember this procedure from the marvel-nccr namespace, perhaps something introduced recently.

> I have a question: how does ansible know there is new release in that repository? Do we need make some change in the role repository?

Once you have the new namespace, you will need to import the repository once.
From then on, the notification line in the travis.yml should inform ansible galaxy about new releases.

2022-01-26 08:01 UTC, csadorf commented
@unkcpz What is the status on this?

2022-03-04 14:01 UTC, closed without merging